# Generated by Django 3.2.6 on 2022-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0009_auto_20210613_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meter_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='power_status',
            field=models.BooleanField(default=False),
        ),
    ]
