# Generated by Django 3.2.6 on 2022-05-28 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meter', '0013_alter_meterdata_unit_usage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdata',
            name='meter_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_bill',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meterdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
