# Generated by Django 3.2.6 on 2022-05-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0014_auto_20220528_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdata',
            name='meter_id',
        ),
        migrations.RemoveField(
            model_name='meterdata',
            name='power_status',
        ),
    ]
