# Generated by Django 3.2.6 on 2022-05-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_auto_20220528_0955'),
        ('meter', '0017_alter_bill_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='meter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authy.profile'),
        ),
    ]
